#!/usr/bin/env python

import sys

import libeeyore.main

def main( argv, stderr ):
	ret = libeeyore.main.main( argv, stderr )
	sys.exit( ret )

if __name__ == "__main__":
	main( sys.argv, sys.stderr )

