#!/usr/bin/env python

# Copyright (C) 2011-2012 Andy Balaam and The Pepper Developers
# Released under the MIT License.  See the file COPYING.txt for details.

import sys

import libpepper.main

def main( argv, stderr ):
	ret = libpepper.main.main( argv, stderr )
	sys.exit( ret )

if __name__ == "__main__":
	main( sys.argv, sys.stderr )

